import { Disclosure } from '@headlessui/react'
import Head from 'next/head';
import Image from 'next/image';

import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useEffect, useState } from 'react';


const navigation = [
  { name: 'Home', href: '/', current: true, id: 0 },
  { name: 'View & Update', href: '/reviews/view', current: false, id: 1 },
  { name: 'Profile', href: '/profile', current: false, id: 2},
]

function classNames(...classes: string[]) {
  return classes.filter(Boolean).join(' ')
}

type LayoutProps = {
  children: React.ReactNode;
}

export default function Layout({ children }: LayoutProps) {
  const [active, setActive] = useState(0);

  useEffect(() => {
    if(window.location.pathname === navigation[0].href){
      setActive(0);
    } else if (window.location.pathname === navigation[1].href){
      setActive(1);
    } else if (window.location.pathname === navigation[2].href){
      setActive(2);
    }
  }, [])

  return (
    <>

      <Head>
        <title>Casama Review System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className="min-h-full">
        <Disclosure as="nav" className="bg-gray-800">
              <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
                <div className="flex h-16 items-center justify-between">
                  <div className="flex items-center">
                    <div className="flex-shrink-0">
                      <Image
                        height={50}
                        width={150}
                        src="/casama_white_logo.png"
                        alt="Your Company"
                      />
                    </div>
                    <div className="hidden md:block">
                      <div className="ml-10 flex items-baseline space-x-4">
                        {navigation.map((item) => (
                          <a
                            key={item.name}
                            href={item.href}
                            className={classNames(
                              (item.id === active)
                                ? 'bg-gray-900 text-white'
                                : 'text-gray-300 hover:bg-gray-700 hover:text-white',
                              'rounded-md px-3 py-2 text-sm font-medium'
                            )}
                            aria-current={item.current ? 'page' : undefined}
                          >
                            {item.name}
                          </a>
                        ))}
                      </div>
                    </div>
                  </div>
                  <ConnectButton />
                </div>
              </div>
        </Disclosure>
        <main>
          <div className="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
            {children}
          </div>
        </main>
      </div>
    </>
  )
}

